version: "3"
services:
  backend:
    container_name: tour-of-heroes-api
    image: tour-of-heroes-api
    build: tour-of-heroes-api/.
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - redis
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - spring.redis.host=redis
    volumes:
      - ~/docker/redis:/redis-service/logs
  # redis
  redis:
    container_name: redis
    image: redis:5.0
    hostname: redis
    ports:
      - '6379:6379'
  frontend:
    container_name: tour-of-heroes-ui
    image: tour-of-heroes-ui
    build: frontend/.
    ports:
      - "4200:4200"
    depends_on:
      - backend
